### ISSUE TITLE
How should we handle versioning?

### ISSUE THREAD

**Issue by stevencarlislewalker** [stevencarlislewalker/thermopic#7]
I would prefer to use the versioning system recommended here:  http://r-pkgs.had.co.nz/description.html

However, I respect that there is an existing system in place.

One thing I would really like to get rid of is the versioning of the file names.  These versions should be implied by the version of the package in which the files live.  It is less error-prone to have a single place for the version of package contents.

**Comment by nyglester** [comment]
Yes - i agree with your suggestions
